In [13]:
import numpy as np
import pandas as pd

Series from lists

In [14]:
#string

country = ['India','Pakistan','USA','Nepal','Srilanka']
pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4    Srilanka
dtype: object

In [15]:
# integers

runs = [13,24,56,78,100]

pd.Series(runs)

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [16]:
# integers

runs = [13,24,56,78,100]

runs_ser = pd.Series(runs)

In [17]:
# custom index

marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']

pd.Series(marks,index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [18]:
#setting a name

marks = pd.Series(marks, index=subjects,name='Nitish ke marks')
marks

maths       67
english     57
science     89
hindi      100
Name: Nitish ke marks, dtype: int64

Series from dict

In [19]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100,
}

marks_series = pd.Series(marks)
marks_series

maths       67
english     57
science     89
hindi      100
dtype: int64

In [20]:
marks_series = pd.Series(marks,name='nitish ke marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: nitish ke marks, dtype: int64

Series attributes

In [21]:
#size
marks_series.size

4

In [22]:
# d type

marks_series.dtype

dtype('int64')

In [23]:
# name

marks_series.name

'nitish ke marks'

In [24]:
# is_unique

marks_series.is_unique

True

In [25]:
pd.Series([1,1,2,3,4,5]).is_unique

False

In [26]:
#index
marks_series.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [27]:
runs_ser.index

RangeIndex(start=0, stop=5, step=1)

In [28]:
type(runs_ser.index)

pandas.core.indexes.range.RangeIndex

In [29]:
marks_series.values

array([ 67,  57,  89, 100])

In [30]:
type(marks_series.values)

numpy.ndarray

Series using read_csv

In [31]:
#with one col
pd.read_csv('subs.csv')

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [32]:
#with one col
type(pd.read_csv('subs.csv'))

pandas.core.frame.DataFrame

In [33]:
#converting it into series
df = pd.read_csv('subs.csv')
series = df.squeeze()

series

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [4]:
import pandas as pd
k = pd.read_csv('kohli_ipl.csv')
k

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [35]:
k = pd.read_csv('kohli_ipl.csv',index_col='match_no').squeeze()

In [36]:
k

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [37]:
boll = pd.read_csv('bollywood.csv')
boll

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [38]:
boll = pd.read_csv('bollywood.csv',index_col = 'movie').squeeze()
boll

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

Series Method

In [7]:
#head and tail
subs = pd.read_csv('subs.csv') 
subs.head()

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [43]:
vk = pd.read_csv('kohli_ipl.csv')
vk.head()

   match_no  runs
0         1     1
1         2    23
2         3    13
3         4    12
4         5     1

In [44]:
vk.head(3)

   match_no  runs
0         1     1
1         2    23
2         3    13

In [58]:
vk.tail(10)

     match_no  runs
205       206     0
206       207     0
207       208     9
208       209    58
209       210    30
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

In [49]:
#sample

boll.sample()

movie
Mickey Virus    Manish Paul
Name: lead, dtype: object

In [50]:
#sample

boll.sample(5)

movie
Department (film)         Sanjay Dutt
Thugs of Hindostan         Aamir Khan
A Flat (film)         Jimmy Sheirgill
Angel (2011 film)         Sumit Arora
Delhi-6                Waheeda Rehman
Name: lead, dtype: object

In [51]:
#value_counts -> boll (bollywood dataset/movies)

boll.value_counts()

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Diganth              1
Parveen Kaur         1
Seema Azmi           1
Akanksha Puri        1
Edwin Fernandes      1
Name: count, Length: 566, dtype: int64

In [59]:
# sort_values -> inplace
vk.sort_values(by='runs')

     match_no  runs
86         87     0
210       211     0
206       207     0
205       206     0
90         91     0
..        ...   ...
163       164   100
119       120   100
122       123   108
125       126   109
127       128   113

[215 rows x 2 columns]